package com.example.projectmanagerapp.ui.theme

import androidx.compose.ui.graphics.Color

// Light
val primaryLight = Color(0xFF2563EB)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFDBE7FF)
val onPrimaryContainerLight = Color(0xFF001C3A)
val secondaryLight = Color(0xFF6366F1)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE0E7FF)
val onSecondaryContainerLight = Color(0xFF1E1B3B)
val tertiaryLight = Color(0xFF14B8A6)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFCCFBF1)
val onTertiaryContainerLight = Color(0xFF134E4A)
val errorLight = Color(0xFFEF4444)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF8FAFC)
val onBackgroundLight = Color(0xFF1A1C1E)
val surfaceLight = Color(0xFFF1F5F9)
val onSurfaceLight = Color(0xFF1A1C1E)
val surfaceVariantLight = Color(0xFFF1F5F9)
val onSurfaceVariantLight = Color(0xFF44464F)
val surfaceContainerLight = Color(0xFFF1F5F9)
val surfaceContainerHighLight = Color(0xFFF1F5F9)
val surfaceContainerHighestLight = Color(0xFFE2E8F0)
val surfaceContainerLowLight = Color(0xFFFAFAFA)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceDimLight = Color(0xFFD7DADD)
val surfaceBrightLight = Color(0xFFF8FAFC)
val outlineLight = Color(0xFFCBD5E1)
val outlineVariantLight = Color(0xFFE2E8F0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2E3134)
val inverseOnSurfaceLight = Color(0xFFEFF1F4)
val inversePrimaryLight = Color(0xFF60A5FA)
val surfaceTintLight = Color(0xFF2563EB)


// Dark
val primaryDark = Color(0xFF60A5FA)
val onPrimaryDark = Color(0xFF003258)
val primaryContainerDark = Color(0xFF004A77)
val onPrimaryContainerDark = Color(0xFFD1E4FF)
val secondaryDark = Color(0xFF818CF8)
val onSecondaryDark = Color(0xFF1E1B3B)
val secondaryContainerDark = Color(0xFF3730A3)
val onSecondaryContainerDark = Color(0xFFE0E7FF)
val tertiaryDark = Color(0xFF2DD4BF)
val onTertiaryDark = Color(0xFF003731)
val tertiaryContainerDark = Color(0xFF115E59)
val onTertiaryContainerDark = Color(0xFFCCFBF1)
val errorDark = Color(0xFFF87171)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0F172A)
val onBackgroundDark = Color(0xFFE2E2E5)
val surfaceDark = Color(0xFF1E293B)
val onSurfaceDark = Color(0xFFE2E2E5)
val surfaceVariantDark = Color(0xFF334155)
val onSurfaceVariantDark = Color(0xFFC4C7C5)
val surfaceContainerDark = Color(0xFF1E293B)
val surfaceContainerHighDark = Color(0xFF334155)
val surfaceContainerHighestDark = Color(0xFF475569)
val surfaceContainerLowDark = Color(0xFF1A1C1E)
val surfaceContainerLowestDark = Color(0xFF0F172A)
val surfaceDimDark = Color(0xFF0F172A)
val surfaceBrightDark = Color(0xFF334155)
val outlineDark = Color(0xFF475569)
val outlineVariantDark = Color(0xFF334155)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E2E5)
val inverseOnSurfaceDark = Color(0xFF2E3134)
val inversePrimaryDark = Color(0xFF2563EB)
val surfaceTintDark = Color(0xFF60A5FA)


